# Generated by Django 5.2.8 on 2025-11-14 00:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alumno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField()),
                ("apellido", models.CharField()),
                ("dni", models.IntegerField()),
                ("creado", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
